
services:
  # API Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: barbara-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - MONGODB_URI=${MONGODB_URI}
      - AVATAR_PROVIDER=${AVATAR_PROVIDER}
      - READY_PLAYER_ME_APP_ID=${READY_PLAYER_ME_APP_ID}
      - READY_PLAYER_ME_API_KEY=${READY_PLAYER_ME_API_KEY}
      - READY_PLAYER_ME_BASE_URL=${READY_PLAYER_ME_BASE_URL}
      - TRYON_DIFFUSION_ENDPOINT=${TRYON_DIFFUSION_ENDPOINT}
      - TRYON_DIFFUSION_TOKEN=${TRYON_DIFFUSION_TOKEN}
      - ASSETS_BASE_URL=${ASSETS_BASE_URL}
      - AVATAR_RATE_LIMIT=${AVATAR_RATE_LIMIT}
      - AVATAR_WORKER_POLL_MS=${AVATAR_WORKER_POLL_MS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - AVATAR_QUEUE_MODE=${AVATAR_QUEUE_MODE}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - AVATAR_QUEUE_NAME=${AVATAR_QUEUE_NAME}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_QUEUE_NAME=${AZURE_QUEUE_NAME}
      - AZURE_QUEUE_POLL_MS=${AZURE_QUEUE_POLL_MS}
    volumes:
      - ./api/logs:/app/logs
    networks:
      - barbara-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ngrok para expor API publicamente
  ngrok:
    image: ngrok/ngrok:latest
    container_name: barbara-ngrok
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"  # Web interface do ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    networks:
      - barbara-network
    depends_on:
      - api

networks:
  barbara-network:
    driver: bridge

volumes:
  api-logs:
    driver: local
